# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.cburris.Demo.Demo
name: Demo
version: ${project.version}
author: Charlie Burris
description: ${project.description}
commands:
  demo:
    description: the based for this plugin
    usage: /<demo> command 
    permission: demo.*
permissions:
  demo.*:
    description: permissions of all demo plugin commands
    default: true
    children:
      demo.message:
        description: gives permission for sample message using the sample command
      demo.spider:
        default: op
      demo.bed:
        description: teleport to bed
      demo xp:
        description: get experience
      demo.sword:
        default: true;
      demo.armor:
        default: true;